# General Configuration
save-player-data: true

# GUI & Chat Configuration
inventory-title: Particle Effects
inventory-size: 54

particle-selected-lore: SELECTED!
effect-already-active: You already have this effect active.
heart:
  isEnabled: true
  name: Heart
  icon: POPPY
  slot: 10
  no-permission-item-lore: You have not unlocked this effect yet.
  no-permission-chat-message: You have not unlocked this effect yet.
lavadrip:
  isEnabled: true
  name: Lava Drip
  icon: LAVA_BUCKET
  slot: 11
  no-permission-item-lore: You have not unlocked this effect yet.
  no-permission-chat-message: You have not unlocked this effect yet.
waterdrip:
  isEnabled: true
  name: Water Drip
  icon: WATER_BUCKET
  slot: 12
  no-permission-item-lore: You have not unlocked this effect yet.
  no-permission-chat-message: You have not unlocked this effect yet.
happyvillager:
  isEnabled: true
  name: Happy Villager
  icon: EMERALD
  slot: 13
  no-permission-item-lore: You have not unlocked this effect yet.
  no-permission-chat-message: You have not unlocked this effect yet.
angryvillager:
  isEnabled: true
  name: Happy Villager
  icon: BLAZE_POWDER
  slot: 14
  no-permission-item-lore: You have not unlocked this effect yet.
  no-permission-chat-message: You have not unlocked this effect yet.
note:
  isEnabled: true
  name: Note
  icon: NOTE_BLOCK
  slot: 15
  no-permission-item-lore: You have not unlocked this effect yet.
  no-permission-chat-message: You have not unlocked this effect yet.
slime:
  isEnabled: true
  name: Slime
  icon: SLIME_BALL
  slot: 16
  no-permission-item-lore: You have not unlocked this effect yet.
  no-permission-chat-message: You have not unlocked this effect yet.
enchantment:
  isEnabled: true
  name: Enchantment
  icon: ENCHANTING_TABLE
  slot: 19
  no-permission-item-lore: You have not unlocked this effect yet.
  no-permission-chat-message: You have not unlocked this effect yet.
critical:
  isEnabled: true
  name: Critical
  icon: IRON_SWORD
  slot: 20
  no-permission-item-lore: You have not unlocked this effect yet.
  no-permission-chat-message: You have not unlocked this effect yet.
magic:
  isEnabled: true
  name: Magic
  icon: POTION
  slot: 21
  no-permission-item-lore: You have not unlocked this effect yet.
  no-permission-chat-message: You have not unlocked this effect yet.
flame:
  isEnabled: true
  name: Flame
  icon: FLINT_AND_STEEL
  slot: 22
  no-permission-item-lore: You have not unlocked this effect yet.
  no-permission-chat-message: You have not unlocked this effect yet.
clear-particle:
  name: Clear Particle Effect
  icon: BARRIER
  slot: 40
  chat-message: You reset your particle effect.