name: ParticleMenu
version: ${project.version}
main: com.jaaakee.particlemenu.ParticleMenu
api-version: 1.13
authors: [ Jaaakee ]
description: A fun, lightweight, and EULA friendly plugin for your players!

commands:
  particlemenu:
    description: ParticleMenu main command, will try to open Particle GUI if no arguments given.
    aliases: [ pm, ptm ]